"""empty message

Revision ID: 8a4e238811f6
Revises: fef6785b235a
Create Date: 2022-04-13 22:59:02.371874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a4e238811f6'
down_revision = 'fef6785b235a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('shows', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'venue', ['venue_id'], ['id'])
    op.alter_column('shows', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
