"""empty message

Revision ID: f37e1e4c8074
Revises: 57dad5b34892
Create Date: 2022-04-09 22:05:16.630761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37e1e4c8074'
down_revision = '57dad5b34892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue')
    # ### end Alembic commands ###
