"""empty message

Revision ID: fef6785b235a
Revises: 5dc0ba782cd4
Create Date: 2022-04-13 21:28:01.539505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef6785b235a'
down_revision = '5dc0ba782cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'shows', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['id'])
    op.drop_column('shows', 'name')
    op.drop_column('shows', 'id')
    op.drop_column('shows', 'venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('shows', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'date_time')
    op.drop_column('shows', 'artist_id')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
